<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.github.chibyhq.playar</groupId>
        <artifactId>playar-boot-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../../poms/boot-parent/pom.xml</relativePath>
	</parent>
	
	<artifactId>playar-client</artifactId>
	<packaging>jar</packaging>

	<name>Playar :: Client API</name>
	<description>Provides a lightweight client API to execute playlists and monitor run sessions</description>

	<properties>
		<test.chiby.client.base.image>busybox:latest</test.chiby.client.base.image>
	</properties>

	<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
		
        <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
				
		<dependency>
			<groupId>com.github.chibyhq.playar</groupId>
			<artifactId>playar-model</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.chibyhq.playar</groupId>
			<artifactId>playar-repositories</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>com.spotify</groupId>
			<artifactId>docker-client</artifactId>
			<version>8.3.2</version>
		</dependency>
	</dependencies>
	
	<profiles>
	  <profile>
	    <id>rpi3</id>
	    <properties>
           <test.chiby.client.base.image>hypriot/armhf-busybox</test.chiby.client.base.image>
		 </properties>
      </profile>
	</profiles>
	
	<build>
	    <plugins>
	      <plugin>
	        <groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-surefire-plugin</artifactId>
	        <version>2.12.4</version>
	        <configuration>
	          <testFailureIgnore>true</testFailureIgnore>
	          <systemPropertyVariables>
	            <test.chiby.client.base.image>${test.chiby.client.base.image}</test.chiby.client.base.image>
	          </systemPropertyVariables>
	        </configuration>
	      </plugin>
	    </plugins>
	  </build>

	
</project>
